// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxfnkrxgncduerpvugmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54Zm5rcnhnbmNkdWVycHZ1Z21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzM3NzQsImV4cCI6MjA2NjIwOTc3NH0.Mn0_-t0KCE4NWuM-DxZrCmgm6BeM7EOR4wjkyfPXQe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);